version: '3.8'

services:
  db:
    image: mongo:latest
    container_name: mongodb_contaner
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 12345678
      MONGO_INITDB_DATABASE: nest
    command:
      - '--logpath'
      - '/var/log/mongodb/mongod.log'
    ports:
      - 27017:27017
    volumes:
      - ./docker/mongodb_data:/data/db
      - ./docker/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6389:6379

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: mongodb://localhost/nest
      REDIS_PORT: 6379
      REDIS_HOST: localhost
      ACCESS_TOKEN_KEY: sf45brh7dfg5w
      ACCESS_TOKEN_EXP: 1d
      REFRESH_TOKEN_KEY: sf45brh7dfg5w
      REFRESH_TOKEN_EXP: 1d
      COOKIE_EXP: 7*24*3600000
    depends_on:
      - db
